// The Symbol + Authored Background manifest (issue #14): the single source of
// truth for every shipped asset's `id`, default `label`, and `kind`.
//
// This is data, not art. The art lives in the per-atlas `*-symbols.svg` files;
// `build-symbols.mjs` windows each `<g id>` cell into a standalone square-viewBox
// Symbol SVG and cross-checks the authored ids against this list. Edit here when
// adding an asset, then author its cell and run `npm run symbols`. See `README.md`.
//
// An asset is one of:
//   - **Source** — authored as a cell in `<atlas>-symbols.svg` (`atlas` field).
//   - **Derived** — generated by rotating another asset (`rotateOf` + `rotate`),
//     so directional sets need only one drawing (author `dpad-right`; down/left/up
//     are rotations of it).
//
// Colour is NOT baked as `currentColor`, nor authored as real colours. Each shape
// is painted in an RGB *sentinel* that encodes the paint role it plays (red → fill,
// blue → border, green → secondary; see `paint-roles.mjs`); the classifier keys on
// that colour and the tool maps each role to an appearance. The per-role *default*
// appearance (e.g. an Xbox A rendered green) is authored at the device scope, not
// baked into the atlas. kind "background" is an Authored Background tile (bumper /
// trigger) that the Style Cascade fill tints; the Input's label (LB/RT…) draws on
// top.
//
// Only the genuinely cross-device art is shared: this pass that's just the stick,
// which lives in `shared-symbols.svg` and every pad reuses it. Everything else —
// face buttons, the d-pad, AND the bumper/trigger tile shapes, which differ per
// platform (Xbox bumper ≠ PlayStation L1) — lives in that device's own atlas.

/**
 * @typedef {object} SymbolAsset
 * @property {string} id
 * @property {string} label
 * @property {"symbol" | "background"} kind
 * @property {string} [atlas] Source assets only: the `<atlas>-symbols.svg` file.
 * @property {string} [rotateOf] Derived assets: the source id to rotate.
 * @property {number} [rotate] Derived assets: clockwise degrees (90 | 180 | 270).
 */

/** @type {SymbolAsset[]} */
export const SYMBOL_MANIFEST = [
  // --- Xbox face buttons — default to the brand palette, tool-configurable -----
  { id: "xbox-a", label: "A", kind: "symbol", atlas: "xbox" },
  { id: "xbox-b", label: "B", kind: "symbol", atlas: "xbox" },
  { id: "xbox-x", label: "X", kind: "symbol", atlas: "xbox" },
  { id: "xbox-y", label: "Y", kind: "symbol", atlas: "xbox" },

  // --- Xbox menu cluster ------------------------------------------------------
  { id: "xbox-view", label: "View", kind: "symbol", atlas: "xbox" },
  { id: "xbox-menu", label: "Menu", kind: "symbol", atlas: "xbox" },

  // --- Xbox bumper/trigger tiles — device-specific shapes ---------------------
  { id: "xbox-bumper", label: "Bumper", kind: "background", atlas: "xbox" },
  { id: "xbox-trigger", label: "Trigger", kind: "background", atlas: "xbox" },

  // --- Shared stick — one glyph reused for both sticks -------------------------
  { id: "stick", label: "Stick", kind: "symbol", atlas: "shared" },

  // --- Xbox d-pad — author "right"; the rest are rotations of it ---------------
  // Device-specific this pass (no shared d-pad yet); promote to "shared" later.
  // The art draws the whole d-pad and emphasises one arm, so it is `cluster`:
  // right in an exported Glyph, skipped by the Device Layout (see SymbolAsset).
  {
    id: "dpad-right",
    label: "D-Pad Right",
    kind: "symbol",
    atlas: "xbox",
    depicts: "cluster",
  },
  {
    id: "dpad-down",
    label: "D-Pad Down",
    kind: "symbol",
    rotateOf: "dpad-right",
    rotate: 90,
    depicts: "cluster",
  },
  {
    id: "dpad-left",
    label: "D-Pad Left",
    kind: "symbol",
    rotateOf: "dpad-right",
    rotate: 180,
    depicts: "cluster",
  },
  {
    id: "dpad-up",
    label: "D-Pad Up",
    kind: "symbol",
    rotateOf: "dpad-right",
    rotate: 270,
    depicts: "cluster",
  },
];
