// The Symbol + Authored Background manifest (issue #14): the single source of
// truth for every shipped asset's `id`, default `label`, and `kind`.
//
// This is data, not art. The art lives in the per-atlas `*-symbols.svg` files;
// `build-symbols.mjs` windows each `<g id>` cell into a standalone square-viewBox
// Symbol SVG and cross-checks the authored ids against this list. Edit here when
// adding an asset, then author its cell and run `npm run symbols`. See `README.md`.
//
// Ids are **bare** — the atlas file a cell lives in supplies its device scope, so
// the Xbox and PlayStation d-pads are both authored as `dpad-right` and neither
// name has to carry a prefix. An asset lists every atlas that draws it in
// `atlases`; the codegen emits one `<atlas>:<id>` entry per atlas, and
// `resolveSymbolSvg` picks the one matching the Glyph's Device. Art in
// `shared-symbols.svg` is emitted unscoped and acts as the fallback for any
// Device that doesn't draw its own.
//
// An asset is one of:
//   - **Source** — authored as a cell in each of its `atlases`.
//   - **Derived** — generated by rotating another asset (`rotateOf` + `rotate`),
//     so directional sets need only one drawing (author `dpad-right`; down/left/up
//     are rotations of it). A derived asset is emitted once per atlas its source
//     is drawn in, so each Device's rotations come from its own art.
//
// Colour is NOT baked as `currentColor`, nor authored as real colours. Each shape
// is painted in an RGB *sentinel* that encodes the paint role it plays (red → fill,
// blue → border, green → secondary; see `paint-roles.mjs`); the classifier keys on
// that colour and the tool maps each role to an appearance. The per-role *default*
// appearance (e.g. an Xbox A rendered green) is authored at the device scope, not
// baked into the atlas. kind "background" is an Authored Background tile (bumper /
// trigger) that the Style Cascade fill tints; the Input's label (LB/RT…) draws on
// top.
//
// Only the genuinely cross-device art is shared: this pass that's just the stick.
// Everything else — face buttons, the d-pad, AND the bumper/trigger tile shapes,
// which differ per platform (an Xbox bumper is not a PlayStation L1) — is drawn
// per device, even where the pads agree on the id.

/**
 * @typedef {object} SymbolAsset
 * @property {string} id
 * @property {string} label
 * @property {"symbol" | "background"} kind
 * @property {string[]} [atlases] Source assets only: every `<atlas>-symbols.svg`
 *   that draws this id. `["shared"]` means one unscoped drawing for all Devices.
 * @property {Record<string, string>} [cells] Per-atlas cell id, where an atlas
 *   draws this asset under a different name — `{ playstation: "R1" }` lets that
 *   pad label its own art R1 while it still resolves as `bumper`. Atlases absent
 *   from this map draw the cell under the bare `id`.
 * @property {string} [rotateOf] Derived assets: the source id to rotate.
 * @property {number} [rotate] Derived assets: clockwise degrees (90 | 180 | 270).
 * @property {"cluster"} [depicts] Art that draws a whole group of Inputs and
 *   emphasises one (the d-pads). Right in an exported Glyph; skipped by the
 *   Device Layout, which already draws the cluster as separate nodes.
 */

/** Every atlas that draws a pad's bumper/trigger/d-pad art. */
const PADS = ["xbox", "playstation"];

/** @type {SymbolAsset[]} */
export const SYMBOL_MANIFEST = [
  // --- Xbox face buttons — default to the brand palette, tool-configurable -----
  { id: "a", label: "A", kind: "symbol", atlases: ["xbox"] },
  { id: "b", label: "B", kind: "symbol", atlases: ["xbox"] },
  { id: "x", label: "X", kind: "symbol", atlases: ["xbox"] },
  { id: "y", label: "Y", kind: "symbol", atlases: ["xbox"] },

  // --- Xbox menu cluster ------------------------------------------------------
  { id: "view", label: "View", kind: "symbol", atlases: ["xbox"] },
  { id: "menu", label: "Menu", kind: "symbol", atlases: ["xbox"] },

  // --- PlayStation face buttons -----------------------------------------------
  { id: "cross", label: "Cross", kind: "symbol", atlases: ["playstation"] },
  { id: "circle", label: "Circle", kind: "symbol", atlases: ["playstation"] },
  { id: "square", label: "Square", kind: "symbol", atlases: ["playstation"] },
  {
    id: "triangle",
    label: "Triangle",
    kind: "symbol",
    atlases: ["playstation"],
  },

  // --- PlayStation menu cluster -----------------------------------------------
  { id: "share", label: "Share", kind: "symbol", atlases: ["playstation"] },
  { id: "options", label: "Options", kind: "symbol", atlases: ["playstation"] },

  // --- Bumper/trigger tiles — one id, drawn to each pad's own shape ------------
  // PlayStation draws these as R1/R2, the names that pad calls them, so `cells`
  // maps its cell ids onto the shared asset id.
  {
    id: "bumper",
    label: "Bumper",
    kind: "background",
    atlases: PADS,
    cells: { playstation: "R1" },
  },
  {
    id: "trigger",
    label: "Trigger",
    kind: "background",
    atlases: PADS,
    cells: { playstation: "R2" },
  },

  // --- Shared stick — one drawing reused by both pads --------------------------
  { id: "stick", label: "Stick", kind: "symbol", atlases: ["shared"] },

  // --- D-pads — each pad draws "right"; the rest are rotations of it -----------
  // The art draws the whole cluster and emphasises one arm, so it is `cluster`:
  // right in an exported Glyph, skipped by the Device Layout (see SymbolAsset).
  {
    id: "dpad-right",
    label: "D-Pad Right",
    kind: "symbol",
    atlases: PADS,
    depicts: "cluster",
  },
  {
    id: "dpad-down",
    label: "D-Pad Down",
    kind: "symbol",
    rotateOf: "dpad-right",
    rotate: 90,
    depicts: "cluster",
  },
  {
    id: "dpad-left",
    label: "D-Pad Left",
    kind: "symbol",
    rotateOf: "dpad-right",
    rotate: 180,
    depicts: "cluster",
  },
  {
    id: "dpad-up",
    label: "D-Pad Up",
    kind: "symbol",
    rotateOf: "dpad-right",
    rotate: 270,
    depicts: "cluster",
  },

  // --- Mouse — one silhouette, drawn six times with a different part emphasised
  // Mouse buttons live on the Keyboard Catalog, so mouse and keyboard art share
  // the one `keyboard` atlas. Like the d-pads these draw the whole cluster and
  // emphasise one part, so they are `cluster`: right in an exported Glyph,
  // skipped by the Device Layout, which now draws a real mouse of its own and
  // would otherwise nest a whole mouse inside one of its buttons.
  //
  // A mouse body is not rotationally symmetric, so unlike the d-pad none of
  // these is a rotation of another — all six are source cells.
  {
    id: "mouse",
    label: "Mouse",
    kind: "symbol",
    atlases: ["keyboard"],
    depicts: "cluster",
  },
  {
    id: "mouse-left",
    label: "Mouse Left",
    kind: "symbol",
    atlases: ["keyboard"],
    depicts: "cluster",
  },
  {
    id: "mouse-right",
    label: "Mouse Right",
    kind: "symbol",
    atlases: ["keyboard"],
    depicts: "cluster",
  },
  {
    id: "mouse-middle",
    label: "Mouse Middle",
    kind: "symbol",
    atlases: ["keyboard"],
    depicts: "cluster",
  },
  {
    id: "mouse-4",
    label: "Mouse 4",
    kind: "symbol",
    atlases: ["keyboard"],
    depicts: "cluster",
  },
  {
    id: "mouse-5",
    label: "Mouse 5",
    kind: "symbol",
    atlases: ["keyboard"],
    depicts: "cluster",
  },

  // --- Keyboard — the keys whose identity is a glyph, not a word --------------
  // Ids match their Catalog ids: the keyboard's Inputs carry no device prefix,
  // so the bare manifest id and the Catalog id are the same string.
  { id: "key-space", label: "Space", kind: "symbol", atlases: ["keyboard"] },
  { id: "key-tab", label: "Tab", kind: "symbol", atlases: ["keyboard"] },
  { id: "key-enter", label: "Enter", kind: "symbol", atlases: ["keyboard"] },
  {
    id: "key-backspace",
    label: "Backspace",
    kind: "symbol",
    atlases: ["keyboard"],
  },
  {
    id: "key-windows",
    label: "Windows",
    kind: "symbol",
    atlases: ["keyboard"],
  },
  {
    id: "key-command",
    label: "Command",
    kind: "symbol",
    atlases: ["keyboard"],
  },

  // --- Arrow keys — "right" is drawn; the rest are rotations of it ------------
  // Same source and same rotation order as the d-pad, so the two directional
  // sets stay identical in shape. These are single Inputs, not clusters: the
  // art is one arrow, so a Layout keycap can draw it directly.
  {
    id: "key-arrow-right",
    label: "Arrow Right",
    kind: "symbol",
    atlases: ["keyboard"],
  },
  {
    id: "key-arrow-down",
    label: "Arrow Down",
    kind: "symbol",
    rotateOf: "key-arrow-right",
    rotate: 90,
  },
  {
    id: "key-arrow-left",
    label: "Arrow Left",
    kind: "symbol",
    rotateOf: "key-arrow-right",
    rotate: 180,
  },
  {
    id: "key-arrow-up",
    label: "Arrow Up",
    kind: "symbol",
    rotateOf: "key-arrow-right",
    rotate: 270,
  },
];
